### ISSUE TITLE
Loader locks the screen when trying to request permission in Android Xamarin Forms

### ISSUE THREAD

**Issue by Law85** [UdaraAlwis/Xamarin-Playground#10]
Good Afternoon

I am getting an issue in android when I try to request permission from the user to access the camera. It shows both the permission dialog and the loader. When I click accept on the permissions that disappears but the loader remain in a frozen state. 

Have you come across this issue or know why the loader is firing when I am requesting permission?

I am firing the permission request using the below code in the page model. 

 await CrossPermissions.Current.RequestPermissionsAsync(new[] { Permission.Camera, Permission.Storage }); (Permissions Plugin).

Thanks
Luke

**Comment by UdaraAlwis** [comment]
Unless you're running the same project solution provided here, please refrain from creating issues since its not related to this project at all. Check your own implementation first.
