### ISSUE TITLE
Not Working on Android XFLoadingPageService

### ISSUE THREAD

**Issue by Nilesh-Jha-14** [UdaraAlwis/Xamarin-Playground#12]
If I am Calling from OnAppearing  , then its showing just empty Page

**Comment by UdaraAlwis** [comment]
Unless you're running the same project solution provided here, please refrain from creating issues since its not related to this project at all. Check your own implementation first.

**Comment by Nilesh-Jha-14** [comment]
I am using the same Project... Just Instead of calling from Button Action. I called the Method from OnAppearing in Xamarin..
