### ISSUE TITLE
Android Toolbar Color changed

### ISSUE THREAD

**Issue by thomasgalliker** [UdaraAlwis/Xamarin-Playground#13]
Hi. Very nice idea with this page loading indicator. However, when I Show the page loading indicator on Android, the Toolbar (at the top of the window) changes to black. It doesnt change back, when I hide the loading page. I checked the Android renderer: It seems like the SetLayout command destroys the toolbar color.

**Comment by cassionandi** [comment]
The Sample project has this issue on API 28. API 27 works fine.

**Comment by cassionandi** [comment]
@thomasgalliker I did some changes in the code and it seems that it solved the problem. 
That a look:

```
window.SetLayout(ViewGroup.LayoutParams.MatchParent, ViewGroup.LayoutParams.MatchParent);
window.ClearFlags(WindowManagerFlags.DimBehind);

window.ClearFlags(WindowManagerFlags.TranslucentStatus);
window.AddFlags(WindowManagerFlags.DrawsSystemBarBackgrounds);
window.SetStatusBarColor(new Android.Graphics.Color(window.StatusBarColor));

window.SetBackgroundDrawable(new ColorDrawable(Android.Graphics.Color.Transparent));
```

**Comment by UdaraAlwis** [comment]
Thanks for sharing @cassionandi :)
