### ISSUE TITLE
Update text at run time?

### ISSUE THREAD

**Issue by dzebas** [UdaraAlwis/Xamarin-Playground#15]
Thanks for this component, works really well!

I did some changes so when calling ShowLoadingPage you can pass a message and it will update text on the fly, don't need to re-create the page:

For example on iOS, works fine:

`public void ShowLoadingPage(string message = null)
{
            // check if the user has set the page or not
            if (!_isInitialized)
                InitLoadingPage(new LoadingIndicatorPage()); // set the default page

            if (!string.IsNullOrEmpty(message))
            {
                var l = _nativeView.Subviews[0].Subviews[1].Subviews[0] as UILabel;

                if (l != null)
                    l.Text = message;
            }

            // showing the native loading page
            UIApplication.SharedApplication.KeyWindow.AddSubview(_nativeView);
}`

Any idea how to make this to work in Android?

Cheers.

**Comment by UdaraAlwis** [comment]
Thanks for sharing, I'm assuming you're referring to the project: https://github.com/UdaraAlwis/Xamarin-Playground/tree/master/XFTransparentPopup

I'm no longer maintaining that project and I've moved to a separate project with a better implementation: https://github.com/UdaraAlwis/Xamarin-Playground/tree/master/XFTransparentPopupUpdate

I recommend using the Rg.PopUp plugin. :) 
Cheers!
