### ISSUE TITLE
Not work with iOS 12.4 devices

### ISSUE THREAD

**Issue by divyesh008** [UdaraAlwis/Xamarin-Playground#19]
![imgpsh_fullsize_anim](https://user-images.githubusercontent.com/10617244/88460462-0026c080-ceba-11ea-93f6-df3c487aa787.png)

iOS 12.4 device shows keyboard with extra space between editor when you click on that part it will take the focus off from editor, and the keyboard gets stuck on for infinite and stays up. To use it again I have to kill the app forcefully.

**Comment by UdaraAlwis** [comment]
@divyesh008  Please be more specific and provide the sample source code for me to investigate. Thank you. 

Required,
- In detailed nature of the Issue
- Referring Project Name
- Sample Project Solution to replicate the issue

**Comment by divyesh008** [comment]
I have fixed my issue using the scroll view, so now I'm closing this.
