### ISSUE TITLE
Support for UWP

### ISSUE THREAD

**Issue by welcometoall** [UdaraAlwis/Xamarin-Playground#2]
Can you support for UWP Platform also?

**Comment by UdaraAlwis** [comment]
@welcometoall Which project are you referring to? although unfortunately I'm not doing much stuff on UWP development, so haven't focused on it often.

**Comment by welcometoall** [comment]
XFCurvedCornersLabelControl

**Comment by ask-himanshu** [comment]
Android App is getting crashed while implementing XFNavBarBackBtnClickOverride. In my main activity of android its giving null pointer exception in Android.Support.V7.Widget.Toolbar. Can you please tell me how to proceed with this.

**Comment by UdaraAlwis** [comment]
As I mentioned before I'm not doing any UWP development at the moment, so won't be able to extend support to it. Cheers!
