### ISSUE TITLE
#AndroidAppCrash

### ISSUE THREAD

**Issue by ask-himanshu** [UdaraAlwis/Xamarin-Playground#3]
Android App is getting crashed while implementing XFNavBarBackBtnClickOverride. In my main activity of android its giving null pointer exception in Android.Support.V7.Widget.Toolbar. Can you please tell me how to proceed with this

**Comment by UdaraAlwis** [comment]
Let me test this first and get back to you.

**Comment by UdaraAlwis** [comment]
Just finished testing this several times, and its working like a charm. Hence I'm closing this issue. @ask-himanshu  Please refrain from opening "issues" unless you have tested the exact project in this repository, not your own implementation.
In that note, make sure you have implemented everything accordingly with the code in this repo. Good luck!
