### ISSUE TITLE
Menus on toolbar not visible

### ISSUE THREAD

**Issue by swapnilghadge2390** [UdaraAlwis/Xamarin-Playground#5]
Hello After applying this i am not able to see action menus on toolbar. Please help

**Comment by UdaraAlwis** [comment]
Which project are you referring to? as you can see this repo is a collection of projects, so you need to be specific.
And please refrain from opening "issues" unless you have tested the exact project in this repository, not your own implementation. 
If you still have any questions refer to the blog post article and present your question there.
Cheers!
