### ISSUE TITLE
XF macOS and WPF

### ISSUE THREAD

**Issue by amirvenus** [UdaraAlwis/Xamarin-Playground#6]
How can I make it work on WPF and macOS platforms of Xamarin.Forms?

**Comment by UdaraAlwis** [comment]
Which project are you referring to? as you can see this repo is a collection of projects, so you need to be specific.
And please refrain from opening "issues" unless you have tested the exact project in this repository, not your own implementation. 
If you still have any questions refer to the blog post article and present your question there.
Cheers!
