### ISSUE TITLE
Does not work if a modal page is currently showing

### ISSUE THREAD

**Issue by DeanoMartino** [UdaraAlwis/Xamarin-Playground#7]
Using this to display a modal page:

    var signupPage = new AccountSignup(viewModel);
    var navPage = new NavigationPage(signupPage);
    await Navigation.PushModalAsync(navPage);

As long as a modal page is displayed the Activity/Loading Indicator Page will not display.  Seems to work fine in all other instances.

**Comment by UdaraAlwis** [comment]
Which project are you referring to? as you can see this repo is a collection of projects, so you need to be specific.
And please refrain from opening "issues" unless you have tested the exact project in this repository, not your own implementation. 
If you still have any questions refer to the blog post article and present your question there.
Cheers!
